name: Deploy Metadata Webtool
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Refresh Data
              run: python refresh_datajs.py

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  folder: static
                  branch: gh-pages
